import type { TitaniumState } from "./types";

const now = Date.now();
const iso = (minutesAgo: number) => new Date(now - minutesAgo * 60_000).toISOString();

export const INITIAL_DEMO_STATE: TitaniumState = {
  barbers: [
    {
      id: "barber-bruno",
      name: "Bruno Titanium",
      specialty: "Cortes modernos e barba",
      active: true,
      status: "busy",
    },
    {
      id: "barber-matheus",
      name: "Matheus",
      specialty: "Degradê e acabamento",
      active: true,
      status: "available",
    },
    {
      id: "barber-diego",
      name: "Diego",
      specialty: "Luzes e progressiva",
      active: true,
      status: "busy",
    },
  ],
  services: [
    {
      id: "service-cut",
      name: "Corte",
      description: "Corte completo com acabamento",
      price: 45,
      durationMinutes: 35,
      active: true,
      category: "Cabelo",
    },
    {
      id: "service-cut-beard",
      name: "Corte + Barba",
      description: "Experiência completa de cabelo e barba",
      price: 75,
      durationMinutes: 60,
      active: true,
      category: "Combo",
    },
    {
      id: "service-lights",
      name: "Corte + Luzes",
      description: "Corte, aplicação e finalização das luzes",
      price: 145,
      durationMinutes: 110,
      active: true,
      category: "Química",
    },
    {
      id: "service-progressive",
      name: "Corte + Progressiva",
      description: "Corte e tratamento de alinhamento dos fios",
      price: 170,
      durationMinutes: 130,
      active: true,
      category: "Química",
    },
    {
      id: "service-beard",
      name: "Barba",
      description: "Modelagem, toalha quente e acabamento",
      price: 35,
      durationMinutes: 25,
      active: true,
      category: "Barba",
    },
  ],
  customers: [
    {
      id: "customer-rafael",
      name: "Rafael Souza",
      phone: "11999990001",
      allergy: "Nenhuma informada",
      createdAt: iso(220),
    },
    {
      id: "customer-andre",
      name: "André Costa",
      phone: "11999990002",
      allergy: "Sensibilidade a produtos com álcool",
      createdAt: iso(520),
    },
    {
      id: "customer-lucas",
      name: "Lucas Ferreira",
      phone: "11999990003",
      allergy: "Nenhuma informada",
      createdAt: iso(20),
    },
  ],
  queue: [
    {
      id: "queue-andre",
      ticket: "T001",
      customerId: "customer-andre",
      customerName: "André Costa",
      displayName: "André C.",
      serviceId: "service-cut-beard",
      serviceName: "Corte + Barba",
      price: 75,
      durationMinutes: 60,
      barberId: "barber-bruno",
      barberName: "Bruno Titanium",
      paymentMethod: "pix",
      status: "in_service",
      allergy: "Sensibilidade a produtos com álcool",
      createdAt: iso(48),
      calledAt: iso(35),
      startedAt: iso(32),
    },
    {
      id: "queue-rafael",
      ticket: "T002",
      customerId: "customer-rafael",
      customerName: "Rafael Souza",
      displayName: "Rafael S.",
      serviceId: "service-cut",
      serviceName: "Corte",
      price: 45,
      durationMinutes: 35,
      barberId: "barber-matheus",
      barberName: "Matheus",
      paymentMethod: "debit",
      status: "called",
      allergy: "Nenhuma informada",
      createdAt: iso(26),
      calledAt: iso(3),
    },
    {
      id: "queue-lucas",
      ticket: "T003",
      customerId: "customer-lucas",
      customerName: "Lucas Ferreira",
      displayName: "Lucas F.",
      serviceId: "service-lights",
      serviceName: "Corte + Luzes",
      price: 145,
      durationMinutes: 110,
      barberId: "barber-diego",
      barberName: "Diego",
      paymentMethod: "credit",
      status: "waiting",
      allergy: "Nenhuma informada",
      createdAt: iso(15),
    },
    {
      id: "queue-marcos",
      ticket: "T097",
      customerId: "customer-marcos",
      customerName: "Marcos Lima",
      displayName: "Marcos L.",
      serviceId: "service-cut",
      serviceName: "Corte",
      price: 45,
      durationMinutes: 35,
      barberId: "barber-bruno",
      barberName: "Bruno Titanium",
      paymentMethod: "pix",
      status: "completed",
      allergy: "Nenhuma informada",
      createdAt: iso(180),
      startedAt: iso(166),
      completedAt: iso(130),
    },
    {
      id: "queue-gabriel",
      ticket: "T098",
      customerId: "customer-gabriel",
      customerName: "Gabriel Alves",
      displayName: "Gabriel A.",
      serviceId: "service-cut-beard",
      serviceName: "Corte + Barba",
      price: 75,
      durationMinutes: 60,
      barberId: "barber-matheus",
      barberName: "Matheus",
      paymentMethod: "debit",
      status: "completed",
      allergy: "Nenhuma informada",
      createdAt: iso(150),
      startedAt: iso(138),
      completedAt: iso(78),
    },
    {
      id: "queue-vinicius",
      ticket: "T099",
      customerId: "customer-vinicius",
      customerName: "Vinícius Rocha",
      displayName: "Vinícius R.",
      serviceId: "service-beard",
      serviceName: "Barba",
      price: 35,
      durationMinutes: 25,
      barberId: "barber-diego",
      barberName: "Diego",
      paymentMethod: "credit",
      status: "completed",
      allergy: "Nenhuma informada",
      createdAt: iso(115),
      startedAt: iso(102),
      completedAt: iso(75),
    },
  ],
  payments: [
    { id: "payment-marcos", queueItemId: "queue-marcos", amount: 45, method: "pix", status: "paid", createdAt: iso(130) },
    { id: "payment-gabriel", queueItemId: "queue-gabriel", amount: 75, method: "debit", status: "paid", createdAt: iso(78) },
    { id: "payment-vinicius", queueItemId: "queue-vinicius", amount: 35, method: "credit", status: "paid", createdAt: iso(75) },
  ],
  updatedAt: new Date().toISOString(),
};
